title: Unsurten lee
description: My Personal Certainty Problems
author: Abdullah Samman
github: https://github.com/evexoio
about: I don't know what I do, but I know that I know how to code.
disqus_shortname: blog-wordhunt-xyz
google_analytics: UA-97099506-9
avatar_url: /static/img/avatar2.jpg

enableTags: true
future: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/evexoio"
    - icon: fa-github
      link: "https://github.com/evexoio"

share:
  twitter_username: evexoio
  fb_appid: 644807489246869

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://blog.wordhunt.xyz"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
